CREATE TABLE Currencies (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
Code VARCHAR(30) NOT NULL,
FullName VARCHAR(30) NOT NULL,
Sign VARCHAR(30) NOT NULL,
UNIQUE (Code) );


CREATE TABLE ExchangeRates (
ID INTEGER PRIMARY KEY AUTO_INCREMENT ,
BaseCurrencyId INTEGER,
TargetCurrencyId INTEGER,
Rate DECIMAL(20, 6) NOT NULL,
FOREIGN KEY (BaseCurrencyId) REFERENCES Currencies(ID),
FOREIGN KEY (TargetCurrencyId) REFERENCES Currencies(ID),
UNIQUE (BaseCurrencyId, TargetCurrencyId) );